---
title: "COVID-19 in New York State"
subtitle: "Source: https://health.ny.gov/diseases/communicable/coronavirus/"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    theme: readable
    vertical_layout: fill
date: 'Last Updated: `r Sys.time()` UTC'
runtime: shiny
resource_files:
- data/covid_count_map/covid_count.dbf
- data/covid_count_map/covid_count.prj
- data/covid_count_map/covid_count.shx
---

```{r setup, include = FALSE, warning = FALSE, message = FALSE}
# Load libraries needed

library(flexdashboard)
library(mapview)
library(leaflet)
library(dichromat)
library(ggthemr)
library(plotly)
library(lubridate)
library(data.table)
library(sp)
library(sf)
library(tidyverse)
library(janitor)

# Load datasets
covid_map <- st_read("data/covid_count_map/covid_count.shp") %>%
  rename(
    "positive_cases" = "pstv_cs",
    "name_nyc" = "nam_nyc"
  )

covid_time_series <- fread("data/covid_time_series/covid_time_series.csv") %>%
  clean_names() %>%
  mutate(date = ymd(date))

top_7 <- covid_time_series %>%
  filter(date == max(date)) %>%
  arrange(desc(positive_cases)) %>%
  head(7) %>%
  select(county) %>%
  pull(county)

covid_time_series <- covid_time_series %>%
  mutate(county = ifelse(county %in% top_7, as.character(county), "Other")) %>%
  group_by(county, date) %>%
  summarise(positive_cases = sum(positive_cases)) %>%
  ungroup()

levels <- covid_time_series %>%
  filter(date == max(date)) %>%
  arrange(desc(positive_cases)) %>%
  select(county) %>%
  pull(county)

covid_time_series$county <- factor(covid_time_series$county, levels = levels)
```

Data source: [New York State Department of Health](https://health.ny.gov/diseases/communicable/coronavirus/)

Column {data-width=650, data-height = 200}
-----------------------------------------------------------------------

###

```{r}
# Include theme for plots
ggthemr("dust")

county_cases_counties <- covid_time_series %>%
  ggplot(aes(x = date, y = positive_cases, group = county, colour = county)) +
  geom_line() +
  geom_point() +
  labs(
    x = "Date",
    y = "Positive Cases",
    title = "Cummulative COVID-19 in New York State counties"
  )

ggplotly(county_cases_counties)
```

### 

```{r}
ggthemr("dust")

covid_ny <- covid_time_series %>%
  select(date, positive_cases) %>%
  group_by(date) %>%
  summarise(positive_cases = sum(positive_cases)) %>%
  mutate(new_cases = positive_cases - lag(positive_cases)) %>%
  ggplot(aes(x = date, y = positive_cases)) +
  geom_line() +
  geom_point() +
  geom_bar(aes(y = new_cases), stat = "identity") +
  labs(
    x = "Date",
    y = "Positive Cases",
    title = "Cummulative COVID-19 in New York State"
  ) +
  theme(legend.position = "right")

ggplotly(covid_ny)
```


Column {data-width = 450}
-----------------------------------------------------------------------

### Covid-19 Confirmed Cases Map 

```{r,message = FALSE, message = FALSE, warning = FALSE}

pal <- colorRampPalette(c("#fae6c0", "#7A6752"))
m <- mapview(covid_map,
  zcol = "positive_cases",
  col.regions = pal,
  alpha = 0.8,
  alpha.regions = 0.9
)

m@map %>% setView(lng = -74, lat = 42, zoom = 6.5)
```



